# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Get to Know Karen Levinzon!
tagline:          'Graphic Design.'
description:      'Learn more about Karen Levinzon and her interests in the fields of design, technology, and computer science. The theme used is a brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Karen Levinzon'
  url:            klkat8@yahoo.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/karen-levinzon/my-respsitory.git
